DROP TABLE LIBRO;

CREATE TABLE LIBRO (
NUMLIBRO INTEGER PRIMARY KEY NOT NULL,
NOMLIBRO VARCHAR(100), 
AUTORLIBRO VARCHAR(100)
);

INSERT INTO LIBRO VALUES(1, 'EL CUERVO', 'EDGAR ALLAN POE');
INSERT INTO LIBRO VALUES(2, 'EN LAS MONTAÑAS DE LA LOCURA', 'H.P. LOVERCRAFT');
INSERT INTO LIBRO VALUES(3, 'ENTREVISTA CON EL VAMPIRO', 'ANNE RICE');

COMMIT;

