-- 1. En una nueva base de datos llamada unidad2-oracle, debemos cargar el archivo
-- unidad2-oracle.sql.

-- Para crear una nueva bases de datos en ORACLE usamos 
-- CREATE DATABASE unidad2-oracle ... 
-- O usamos el "Asistente de configuracion de Bases de Datos" incluido en Oracle.

-- Creamos un nuevo usuario (esquema) y una nueva conexión
-- CREATE USER ##unidad2-oracle IDENTIFIED BY uni2;
-- GRANT ALL PRIVILEGES TO ##unidad2-oracle;
-- DISCONNECT;
-- CONNECT ##unidad2-oracle/uni2;

-- Cargamos el script unidad2-oracle.sql
/*
DROP TABLE detalle_compra;
DROP TABLE compra;
DROP TABLE cliente;
DROP TABLE producto;
DROP SEQUENCE cliente_seq;
DROP SEQUENCE COMPRA_SEQ;
DROP SEQUENCE DETALLE_COMPRA_SEQ;
DROP SEQUENCE PRODUCTO_SEQ;
*/


CREATE SEQUENCE cliente_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
 
CREATE TABLE cliente (
    id NUMBER NOT NULL PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    email VARCHAR2(40) NOT NULL UNIQUE
);

CREATE SEQUENCE compra_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE compra (
    id NUMBER NOT NULL PRIMARY KEY,
    cliente_id NUMBER NOT NULL REFERENCES cliente(id),
    fecha date
);

CREATE SEQUENCE producto_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
CREATE TABLE producto (
    id NUMBER NOT NULL PRIMARY KEY,
    descripcion VARCHAR2(500) NOT NULL,
    stock NUMBER CHECK (stock >= 0),
    precio NUMBER CHECK (precio >= 0)
);

CREATE SEQUENCE detalle_compra_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE detalle_compra (
    id NUMBER NOT NULL PRIMARY KEY,
    producto_id NUMBER NOT NULL REFERENCES producto(id),
    compra_id NUMBER NOT NULL REFERENCES compra(id),
    cantidad NUMBER
);

INSERT INTO CLIENTE (ID, NOMBRE, EMAIL) VALUES (CLIENTE_SEQ.nextval, 'usuario01', 'usuario01@gmail.com');
INSERT INTO CLIENTE (ID, NOMBRE, EMAIL) VALUES (CLIENTE_SEQ.nextval, 'usuario02', 'usuario02@yahoo.com');
INSERT INTO CLIENTE (ID, NOMBRE, EMAIL) VALUES (CLIENTE_SEQ.nextval, 'usuario03', 'usuario03@hotmail.com');
INSERT INTO CLIENTE (ID, NOMBRE, EMAIL) VALUES (CLIENTE_SEQ.nextval, 'usuario04', 'usuario04@hotmail.com');
INSERT INTO CLIENTE (ID, NOMBRE, EMAIL) VALUES (CLIENTE_SEQ.nextval, 'usuario05', 'usuario05@yahoo.com');
INSERT INTO CLIENTE (ID, NOMBRE, EMAIL) VALUES (CLIENTE_SEQ.nextval, 'usuario06', 'usuario06@hotmail.com');
INSERT INTO CLIENTE (ID, NOMBRE, EMAIL) VALUES (CLIENTE_SEQ.nextval, 'usuario07', 'usuario07@yahoo.com');
INSERT INTO CLIENTE (ID, NOMBRE, EMAIL) VALUES (CLIENTE_SEQ.nextval, 'usuario08', 'usuario08@yahoo.com');
INSERT INTO CLIENTE (ID, NOMBRE, EMAIL) VALUES (CLIENTE_SEQ.nextval, 'usuario09', 'usuario09@hotmail.com');
INSERT INTO CLIENTE (ID, NOMBRE, EMAIL) VALUES (CLIENTE_SEQ.nextval, 'usuario010', 'usuario010@hotmail.com');


INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 4, TO_DATE('2020-02-12', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 5, TO_DATE('2020-03-14', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 10, TO_DATE('2020-02-07', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 9, TO_DATE('2020-04-25', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 7, TO_DATE('2020-04-03', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 2, TO_DATE('2020-03-23', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 9, TO_DATE('2020-03-11', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 3, TO_DATE('2020-04-21', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 2, TO_DATE('2020-02-24', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 10, TO_DATE('2020-04-18', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 3, TO_DATE('2020-04-22', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 8, TO_DATE('2020-03-22', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 10, TO_DATE('2020-02-20', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 9, TO_DATE('2020-02-07', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 3, TO_DATE('2020-04-25', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 4, TO_DATE('2020-03-20', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 9, TO_DATE('2020-02-22', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 8, TO_DATE('2020-02-17', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 10, TO_DATE('2020-03-14', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 9, TO_DATE('2020-03-07', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 6, TO_DATE('2020-04-28', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 5, TO_DATE('2020-02-06', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 10, TO_DATE('2020-01-31', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 3, TO_DATE('2020-02-15', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 9, TO_DATE('2020-03-12', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 1, TO_DATE('2020-01-31', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 10, TO_DATE('2020-04-08', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 3, TO_DATE('2020-03-20', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 9, TO_DATE('2020-03-16', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 5, TO_DATE('2020-04-09', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 1, TO_DATE('2020-03-29', 'yyyy-mm-dd'));
INSERT INTO COMPRA (ID, CLIENTE_ID, FECHA) VALUES(COMPRA_SEQ.nextval, 2, TO_DATE('2020-03-29', 'yyyy-mm-dd'));

INSERT INTO PRODUCTO (ID, DESCRIPCION, STOCK, PRECIO) VALUES(PRODUCTO_SEQ.nextval, 'producto1', 6, 9107);
INSERT INTO PRODUCTO (ID, DESCRIPCION, STOCK, PRECIO) VALUES(PRODUCTO_SEQ.nextval, 'producto2', 5, 1760);
INSERT INTO PRODUCTO (ID, DESCRIPCION, STOCK, PRECIO) VALUES(PRODUCTO_SEQ.nextval, 'producto3', 9, 9449);
INSERT INTO PRODUCTO (ID, DESCRIPCION, STOCK, PRECIO) VALUES(PRODUCTO_SEQ.nextval, 'producto4', 8, 194);
INSERT INTO PRODUCTO (ID, DESCRIPCION, STOCK, PRECIO) VALUES(PRODUCTO_SEQ.nextval, 'producto5', 10, 3764);
INSERT INTO PRODUCTO (ID, DESCRIPCION, STOCK, PRECIO) VALUES(PRODUCTO_SEQ.nextval, 'producto6', 6, 8655);
INSERT INTO PRODUCTO (ID, DESCRIPCION, STOCK, PRECIO) VALUES(PRODUCTO_SEQ.nextval, 'producto7', 4, 2875);
INSERT INTO PRODUCTO (ID, DESCRIPCION, STOCK, PRECIO) VALUES(PRODUCTO_SEQ.nextval, 'producto8', 0, 8923);
INSERT INTO PRODUCTO (ID, DESCRIPCION, STOCK, PRECIO) VALUES(PRODUCTO_SEQ.nextval, 'producto9', 4, 4219);
INSERT INTO PRODUCTO (ID, DESCRIPCION, STOCK, PRECIO) VALUES(PRODUCTO_SEQ.nextval, 'producto10', 1, 3001);
INSERT INTO PRODUCTO (ID, DESCRIPCION, STOCK, PRECIO) VALUES(PRODUCTO_SEQ.nextval, 'producto11', 9, 7993);
INSERT INTO PRODUCTO (ID, DESCRIPCION, STOCK, PRECIO) VALUES(PRODUCTO_SEQ.nextval, 'producto12', 3, 8504);
INSERT INTO PRODUCTO (ID, DESCRIPCION, STOCK, PRECIO) VALUES(PRODUCTO_SEQ.nextval, 'producto13', 10, 2415);
INSERT INTO PRODUCTO (ID, DESCRIPCION, STOCK, PRECIO) VALUES(PRODUCTO_SEQ.nextval, 'producto14', 5, 3824);
INSERT INTO PRODUCTO (ID, DESCRIPCION, STOCK, PRECIO) VALUES(PRODUCTO_SEQ.nextval, 'producto15', 10, 7358);
INSERT INTO PRODUCTO (ID, DESCRIPCION, STOCK, PRECIO) VALUES(PRODUCTO_SEQ.nextval, 'producto16', 7, 3631);
INSERT INTO PRODUCTO (ID, DESCRIPCION, STOCK, PRECIO) VALUES(PRODUCTO_SEQ.nextval, 'producto17', 3, 4467);
INSERT INTO PRODUCTO (ID, DESCRIPCION, STOCK, PRECIO) VALUES(PRODUCTO_SEQ.nextval, 'producto18', 2, 9383);
INSERT INTO PRODUCTO (ID, DESCRIPCION, STOCK, PRECIO) VALUES(PRODUCTO_SEQ.nextval, 'producto19', 6, 1140);
INSERT INTO PRODUCTO (ID, DESCRIPCION, STOCK, PRECIO) VALUES(PRODUCTO_SEQ.nextval, 'producto20', 4, 102);

INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 2, 2, 9);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 7, 6, 5);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 16, 23, 1);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 10, 13, 4);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 7, 8, 2);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 2, 14, 6);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 19, 8, 7);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 7, 19, 5);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 17, 3, 5);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 2, 3, 5);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 16, 27, 8);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 16, 10, 8);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 13, 14, 8);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 3, 30, 4);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 13, 15, 2);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 20, 21, 5);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 15, 21, 2);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 15, 16, 3);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 16, 19, 9);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 1, 6, 10);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 17, 1, 7);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 18, 1, 9);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 20, 4, 8);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 16, 4, 9);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 14, 5, 6);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 17, 7, 2);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 17, 9, 6);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 18, 11, 4);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 20, 12, 7);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 3, 17, 5);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 2, 18, 10);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 20, 20, 1);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 10, 22, 10);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 18, 24, 2);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 3, 25, 10);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 3, 26, 4);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 3, 28, 2);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 11, 29, 7);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 9, 31, 5);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 1, 32, 3);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 2, 32, 3);
INSERT INTO DETALLE_COMPRA (ID, PRODUCTO_ID, COMPRA_ID, CANTIDAD) VALUES(DETALLE_COMPRA_SEQ.nextval, 8, 32, 3);

commit;

-- 2. El cliente usuario01 ha realizado la siguiente compra:
-- Producto: producto9.
-- Cantidad: 5.
-- Fecha: fecha del sistema.
-- Utiliza lo que aprendiste sobre transacciones para almacenar los hechos que ocurrieron en
-- este punto. Luego, comprueba los resultados mediante otra consulta, enfocando nuestra
-- atención en el valor del stock, es decir, podremos ver si fue efectivamente descontado.

SET TRANSACTION NAME 'compra_usuario01';

INSERT INTO compra VALUES (COMPRA_SEQ.nextval, (SELECT id FROM cliente WHERE nombre = 'usuario01'), 
TO_DATE(SYSDATE, 'DD-MM-YYYY'));

UPDATE producto SET stock = (stock - 5) WHERE descripcion = 'producto9';

INSERT INTO detalle_compra VALUES (DETALLE_COMPRA_SEQ.nextval, (SELECT id FROM producto WHERE descripcion = 'producto9'), COMPRA_SEQ.currval, 5); 

SELECT id, descripcion, stock FROM producto WHERE descripcion = 'producto9';

-- El UPDATE no fue realizado por falta de Stock, hay que utilizar rollback
-- para anular el INSERT INTO de la compra fallida.

ROLLBACK;

-- 3. El cliente usuario02 ha realizado la siguiente compra:
-- Producto: producto1, producto2, producto8.
-- Cantidad: 3 de cada producto.
-- Fecha: fecha del sistema.
-- Mediante el uso de transacciones, realiza las consultas correspondientes para este
-- requerimiento y luego consulta la tabla producto para validar que si alguno de ellos se queda
-- sin stock, no se realice la compra.

SET TRANSACTION NAME 'compra_usuario02';

INSERT INTO compra VALUES (COMPRA_SEQ.nextval, (SELECT id FROM cliente WHERE nombre = 'usuario02'), 
TO_DATE(SYSDATE, 'DD-MM-YYYY'));

UPDATE producto SET stock = stock - 3 WHERE descripcion = 'producto1';

INSERT INTO detalle_compra VALUES (DETALLE_COMPRA_SEQ.nextval, (SELECT id FROM producto WHERE descripcion = 'producto1'), COMPRA_SEQ.currval, 3); 

SAVEPOINT compra33_producto1;

UPDATE producto SET stock = stock - 3 WHERE descripcion = 'producto2';

INSERT INTO detalle_compra VALUES (DETALLE_COMPRA_SEQ.nextval, (SELECT id FROM producto WHERE descripcion = 'producto2'), COMPRA_SEQ.currval, 3); 

SAVEPOINT compra33_producto2;

UPDATE producto SET stock = stock - 3 WHERE descripcion = 'producto8';

INSERT INTO detalle_compra VALUES (DETALLE_COMPRA_SEQ.nextval, (SELECT id FROM producto WHERE descripcion = 'producto8'), COMPRA_SEQ.currval, 3); 

SELECT id, descripcion, stock FROM producto 
WHERE descripcion IN ('producto1', 'producto2', 'producto8');

-- El tercer UPDATE no fue realizado por falta de Stock, hay que utilizar rollback
-- para anular el INSERT INTO y los primeros dos UPDATE de la compra fallida.

ROLLBACK;

-- 4. Realizar las siguientes consultas:
-- A. Deshabilitar el AUTOCOMMIT.
-- B. Insertar un nuevo cliente.
-- C. Confirmar que fue agregado en la tabla cliente.
-- D. Realizar un ROLLBACK.
-- E. Confirmar que se restauró la información, sin considerar la inserción del punto b.
-- F. Habilitar de nuevo el AUTOCOMMIT

SET AUTOCOMMIT OFF;

SET TRANSACTION NAME 'parte4';

INSERT INTO cliente VALUES (CLIENTE_SEQ.nextval, 'usuario11', 'usuario11@yahoo.com');

SELECT * FROM cliente;

ROLLBACK;

SELECT * FROM cliente;

SET AUTOCOMMIT ON;
